org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# O projeto pode estar em uma unidade diferente do cache Pub no Windows.
# Desativar o cache incremental evita falhas de caminho ao gerar o APK.
kotlin.incremental=false
